### ISSUE TITLE
Prototype pollution in refify.js

### ISSUE THREAD

**Issue by lelecolacola123** [grncdr/refify#3]
Prototype pollution vulnerability in function set() in node_modules\refify\refify.js in refify1.0.1.
The function set and the variable obj lead to Prototype pollution in line 106

https://cheatsheetseries.owasp.org/cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.html

**Comment by grncdr** [comment]
PRs welcome, but if you actually use this lib you might want to just fork it.

<img width="377" alt="grafik" src="https://github.com/grncdr/refify/assets/82634/6d5717a9-7cc8-4029-af36-3734015f1a78">
